// Package lockfile reads and writes bunpy.lock. The lockfile
// freezes one entry per direct dependency captured by bunpy add.
// v0.1.4 supports schema version 1; v0.1.5 fills in transitive
// entries against the same shape.
package lockfile

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// Schema version. Bump when the on-disk shape changes.
const Version = 1

// Lock is the parsed bunpy.lock.
type Lock struct {
	Version     int       `toml:"version"`
	Generated   time.Time `toml:"generated"`
	ContentHash string    `toml:"content-hash"`
	Packages    []Package `toml:"package"`
}

// Package is one row in the lockfile.
type Package struct {
	Name     string `toml:"name"`
	Version  string `toml:"version"`
	Filename string `toml:"filename"`
	URL      string `toml:"url"`
	Hash     string `toml:"hash"`
}

// ErrNotFound is returned by Read when bunpy.lock does not exist.
var ErrNotFound = errors.New("lockfile: not found")

// Read parses bunpy.lock at path. A missing file returns
// ErrNotFound (wrapped with the path).
func Read(path string) (*Lock, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("%w: %s", ErrNotFound, path)
		}
		return nil, err
	}
	return Parse(data)
}

// Parse reads bunpy.lock bytes.
func Parse(data []byte) (*Lock, error) {
	l := &Lock{}
	text := string(data)
	lines := strings.Split(text, "\n")
	var (
		inPackage bool
		curr      Package
	)
	flush := func() {
		if inPackage {
			l.Packages = append(l.Packages, curr)
		}
		curr = Package{}
		inPackage = false
	}
	for _, raw := range lines {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if line == "[[package]]" {
			flush()
			inPackage = true
			continue
		}
		k, v, ok := splitKV(line)
		if !ok {
			return nil, fmt.Errorf("lockfile: malformed line %q", raw)
		}
		if !inPackage {
			switch k {
			case "version":
				n, err := parseInt(v)
				if err != nil {
					return nil, fmt.Errorf("lockfile: version: %w", err)
				}
				l.Version = n
			case "generated":
				t, err := time.Parse(time.RFC3339, unquote(v))
				if err != nil {
					return nil, fmt.Errorf("lockfile: generated: %w", err)
				}
				l.Generated = t
			case "content-hash":
				l.ContentHash = unquote(v)
			default:
				return nil, fmt.Errorf("lockfile: unknown header key %q", k)
			}
			continue
		}
		switch k {
		case "name":
			curr.Name = unquote(v)
		case "version":
			curr.Version = unquote(v)
		case "filename":
			curr.Filename = unquote(v)
		case "url":
			curr.URL = unquote(v)
		case "hash":
			curr.Hash = unquote(v)
		default:
			return nil, fmt.Errorf("lockfile: unknown package key %q", k)
		}
	}
	flush()
	if l.Version == 0 {
		l.Version = Version
	}
	return l, nil
}

func splitKV(s string) (string, string, bool) {
	eq := strings.IndexByte(s, '=')
	if eq < 0 {
		return "", "", false
	}
	return strings.TrimSpace(s[:eq]), strings.TrimSpace(s[eq+1:]), true
}

func unquote(s string) string {
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}

func parseInt(s string) (int, error) {
	n := 0
	if s == "" {
		return 0, errors.New("empty integer")
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c < '0' || c > '9' {
			return 0, fmt.Errorf("non-digit %q", c)
		}
		n = n*10 + int(c-'0')
	}
	return n, nil
}

// Bytes serialises the lock to canonical TOML. Packages are
// sorted by PEP 503-normalised name. Line endings are LF.
func (l *Lock) Bytes() []byte {
	var sb strings.Builder
	sb.WriteString("# bunpy.lock - generated by bunpy. Do not edit by hand.\n")
	if l.Version == 0 {
		l.Version = Version
	}
	fmt.Fprintf(&sb, "version = %d\n", l.Version)
	if !l.Generated.IsZero() {
		fmt.Fprintf(&sb, "generated = %q\n", l.Generated.UTC().Format(time.RFC3339))
	}
	if l.ContentHash != "" {
		fmt.Fprintf(&sb, "content-hash = %q\n", l.ContentHash)
	}

	pkgs := append([]Package(nil), l.Packages...)
	sort.SliceStable(pkgs, func(i, j int) bool {
		return Normalize(pkgs[i].Name) < Normalize(pkgs[j].Name)
	})
	for _, p := range pkgs {
		sb.WriteString("\n[[package]]\n")
		fmt.Fprintf(&sb, "name = %q\n", p.Name)
		fmt.Fprintf(&sb, "version = %q\n", p.Version)
		fmt.Fprintf(&sb, "filename = %q\n", p.Filename)
		fmt.Fprintf(&sb, "url = %q\n", p.URL)
		fmt.Fprintf(&sb, "hash = %q\n", p.Hash)
	}
	return []byte(sb.String())
}

// WriteFile writes the lockfile to path with 0o644.
func (l *Lock) WriteFile(path string) error {
	return os.WriteFile(path, l.Bytes(), 0o644)
}

// Upsert inserts a package by PEP 503-normalised name, replacing
// any existing entry with the same normalised name.
func (l *Lock) Upsert(p Package) {
	want := Normalize(p.Name)
	for i := range l.Packages {
		if Normalize(l.Packages[i].Name) == want {
			l.Packages[i] = p
			return
		}
	}
	l.Packages = append(l.Packages, p)
}

// Remove drops the package with the given name (PEP 503
// normalised). Returns true when a row was removed.
func (l *Lock) Remove(name string) bool {
	want := Normalize(name)
	for i := range l.Packages {
		if Normalize(l.Packages[i].Name) == want {
			l.Packages = append(l.Packages[:i], l.Packages[i+1:]...)
			return true
		}
	}
	return false
}

// Find returns the package row for name (PEP 503 normalised) or
// (Package{}, false).
func (l *Lock) Find(name string) (Package, bool) {
	want := Normalize(name)
	for _, p := range l.Packages {
		if Normalize(p.Name) == want {
			return p, true
		}
	}
	return Package{}, false
}

// Normalize is PEP 503: lower-case and collapse runs of -_. into
// a single -.
func Normalize(s string) string {
	s = strings.ToLower(s)
	var sb strings.Builder
	prev := byte(0)
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '-' || c == '_' || c == '.' {
			if prev == '-' {
				continue
			}
			sb.WriteByte('-')
			prev = '-'
			continue
		}
		sb.WriteByte(c)
		prev = c
	}
	return sb.String()
}

// HashDependencies returns sha256:<hex> over the sorted, trimmed
// dependency specs. Used as the lockfile's content-hash so a
// drift check can detect pyproject mutations without re-resolving.
func HashDependencies(deps []string) string {
	cleaned := make([]string, 0, len(deps))
	for _, d := range deps {
		t := strings.TrimSpace(d)
		if t == "" {
			continue
		}
		cleaned = append(cleaned, t)
	}
	sort.Strings(cleaned)
	h := sha256.New()
	for _, c := range cleaned {
		h.Write([]byte(c))
		h.Write([]byte{'\n'})
	}
	return "sha256:" + hex.EncodeToString(h.Sum(nil))
}
