#!/usr/bin/env bash
#
# feature-coverage.sh: print a Markdown table of bunpy-vs-Bun feature
# coverage from a small index file. The source of truth lives in
# scripts/coverage.tsv (status \t bun-feature \t bunpy-feature \t notes)
# so adding a row in the source updates docs/COVERAGE.md atomically.

set -euo pipefail

cd "$(dirname "$0")/.."

src=scripts/coverage.tsv

if [ ! -f "$src" ]; then
  echo "missing $src" >&2
  exit 1
fi

cat <<'EOF'
# Coverage

Tracks bunpy's progress against Bun's feature surface. Generated by
`scripts/feature-coverage.sh` from `scripts/coverage.tsv`. Status
codes:

- `done`: implemented and shipped in a tagged release.
- `wip`: currently being landed.
- `next`: next on the ladder per `docs/ROADMAP.md`.
- `todo`: planned, not yet started.
- `skip`: intentionally out of scope (see `docs/DEVIATIONS.md`).

| Status | Bun                | bunpy                | Notes |
|--------|--------------------|----------------------|-------|
EOF

awk -F'\t' 'NF >= 3 { printf "| %-6s | %-18s | %-20s | %s |\n", $1, $2, $3, $4 }' "$src"
