#!/usr/bin/env bash
# Generates runtime/stdlib_index.go from goipy's switch in
# vm/asyncio.go. Run after bumping the goipy pin in
# scripts/sync-deps.sh. CI runs this into a tempdir and diffs
# against the checked-in file to catch drift.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GOIPY_VM="$ROOT/.deps/goipy/vm/asyncio.go"
if [ ! -f "$GOIPY_VM" ]; then
  echo "sync-stdlib-index: $GOIPY_VM missing; run scripts/sync-deps.sh first" >&2
  exit 1
fi

OUT="${1:-$ROOT/runtime/stdlib_index.go}"

names="$(awk '
  match($0, /case "[a-zA-Z0-9_.]+":/) {
    s = substr($0, RSTART + 6, RLENGTH - 8)
    print s
  }
' "$GOIPY_VM" | LC_ALL=C sort -u)"

mkdir -p "$(dirname "$OUT")"

{
  echo "// Code generated by scripts/sync-stdlib-index.sh. DO NOT EDIT."
  echo ""
  echo "package runtime"
  echo ""
  echo "// Modules lists the Python stdlib modules embedded by the goipy"
  echo "// build that bunpy is wired against. The list is sorted and"
  echo "// deduplicated. Regenerate with scripts/sync-stdlib-index.sh."
  echo "var Modules = []string{"
  while IFS= read -r m; do
    [ -n "$m" ] || continue
    printf '\t"%s",\n' "$m"
  done <<< "$names"
  echo "}"
} > "$OUT"

echo "wrote $OUT ($(printf '%s' "$names" | wc -l | tr -d ' ') modules)"
