#!/usr/bin/env bash
# Generates runtime/stdlib_index.go from goipy's vm/asyncio.go.
# Reads goipy version from go.mod and resolves the source via the
# Go module cache (go env GOMODCACHE). Run after bumping goipy in
# go.mod. CI runs this into a tempdir and diffs against the
# checked-in file to catch drift.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Resolve goipy version from go.mod.
GOIPY_VERSION="$(awk '/github\.com\/tamnd\/goipy / { print $2 }' "$ROOT/go.mod")"
if [ -z "$GOIPY_VERSION" ]; then
  echo "sync-stdlib-index: could not find github.com/tamnd/goipy in go.mod" >&2
  exit 1
fi

GOMODCACHE="$(go env GOMODCACHE)"
GOIPY_VM="$GOMODCACHE/github.com/tamnd/goipy@${GOIPY_VERSION}/vm/asyncio.go"
if [ ! -f "$GOIPY_VM" ]; then
  echo "sync-stdlib-index: $GOIPY_VM missing; run: go mod download github.com/tamnd/goipy@${GOIPY_VERSION}" >&2
  exit 1
fi

OUT="${1:-$ROOT/runtime/stdlib_index.go}"

names="$(awk '
  match($0, /case "[a-zA-Z0-9_.]+":/) {
    s = substr($0, RSTART + 6, RLENGTH - 8)
    print s
  }
' "$GOIPY_VM" | LC_ALL=C sort -u)"

mkdir -p "$(dirname "$OUT")"

{
  echo "// Code generated by scripts/sync-stdlib-index.sh. DO NOT EDIT."
  echo ""
  echo "package runtime"
  echo ""
  echo "// Modules lists the Python stdlib modules embedded by the goipy"
  echo "// build that bunpy is wired against. The list is sorted and"
  echo "// deduplicated. Regenerate with scripts/sync-stdlib-index.sh."
  echo "var Modules = []string{"
  while IFS= read -r m; do
    [ -n "$m" ] || continue
    printf '\t"%s",\n' "$m"
  done <<< "$names"
  echo "}"
} > "$OUT"

echo "wrote $OUT ($(printf '%s' "$names" | wc -l | tr -d ' ') modules)"
